name: stripe
version: 1.3.0
authors:
  - Matias Meno <m@tias.me>
  - Martin Flucka <martin.flucka@gmail.com>
description: Stripe API wrapper
homepage: https://github.com/exitlive/stripe-dart
documentation: https://github.com/exitlive/stripe-dart
environment:
  sdk: '>=1.9.0 <3.0.0'
dependencies:
  http: ^0.11.2
  logging: ^0.11.0
dev_dependencies:
  test: ^1.0.0
