name: stripe_dart_flutter
version: 0.1.0
authors:
  - Tanner Davis <tannerdavisr@gmail.com>
  - Brandon Derbidge <brander81@gmail.com>
description: Stripe API wrapper written for Flutter/Dart applications. Forked from [this repo](https://gitlab.com/exitlive/stripe-dart) and changed to be compatible with Flutter.
homepage: https://github.com/cholojuanito/stripe_dart_flutter
repository: https://github.com/cholojuanito/stripe_dart_flutter
issue_tracker: https://github.com/cholojuanito/stripe_dart_flutter/issues

environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  http: ">=0.11.2 <0.13.0"
  logging: ^0.11.0
dev_dependencies:
  test: ^1.0.0
